version: '3'

services:

  web:
    build:
      context: .
      dockerfile: images/nginx/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/code/
    links:
      - php

  php:
    build:
      context: .
      dockerfile: images/php/Dockerfile
    volumes:
      - .:/code/
      - "./images/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: images/mysql/Dockerfile
    command: ['--default-authentication-plugin=mysql_native_password']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret_root_password
      MYSQL_DATABASE: prestashop
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    security_opt:
      - seccomp:unconfined
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 9906:3306    


  phpadmin:
    build:
      context: .
      dockerfile: images/phpmyadmin/Dockerfile
    depends_on:
      - db
      - php
    ports:
      - "9010:80"
    environment:
      PMA_HOST: "db"
      PMA_PORT: "3306"
